#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION_FULL "2018.2.10f1_674aa5a67ed5"
#define UNITY_VERSION_FULL_NICE "2018.2.10f1 (674aa5a67ed5)"
#define UNITY_VERSION_BLD 6769317
#define UNITY_VERSION_DATE 1537435673
#define UNITY_VERSION_WIN "2018.2.10.6769317"
#define UNITY_VERSION_BRANCH "2018.2/release"
