#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION "2018.2.10f1"
#define UNITY_VERSION_DIGITS "2018.2.10"
#define UNITY_VERSION_SUFFIX "f1"
#define UNITY_VERSION_VER 2018
#define UNITY_VERSION_MAJ 2
#define UNITY_VERSION_MIN 10
#define UNITY_IS_BETA 0
